version: '3.8'

services:
  hyperion-elite-bot:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: hyperion-elite-bot-24x7
    restart: always
    
    environment:
      # No environment variables needed - all hardcoded for zero-config
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - TZ=UTC
    
    volumes:
      # Persistent storage for 24/7 operation
      - hyperion-hits:/app/hits
      - hyperion-logs:/app/logs
      - hyperion-temp:/app/temp
    
    networks:
      - hyperion-network
    
    # Resource limits (adjust based on your VPS)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.telegram.org', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp

networks:
  hyperion-network:
    driver: bridge